(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "clojure-test-mode")
(depends-on "grizzl")
(depends-on "js2-mode")
(depends-on "js2-refactor")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "rainbow-delimiters")
(depends-on "smex")
(depends-on "zenburn-theme")